# IaC file for Render Blueprint
previews:
  generation: automatic
services:
- type: web
  name: hr_suite_spot
  runtime: python
  repo: https://github.com/CovertRob/hr_suite_spot
  plan: Professional
  envVars:
  - fromGroup: Live HRSS ENV
  region: oregon
  buildCommand: poetry install
  startCommand: gunicorn hr_suite_spot.wsgi:app -b :$PORT
  domains:
  - www.hrsuitespot.com
  - hrsuitespot.com
  maintenanceMode:
    enabled: true
version: "1"

databases:
  - name: HRSS_DB                 # Render resource name
    plan: Professional            # live plan
    region: oregon
    databaseName: hrss_db         # initial DB name
    user: hrss_db_user            # initial DB user